build(upload): CurseForge support

diff --git a/dev/upload b/dev/upload
--- a/dev/upload
+++ b/dev/upload
@@ -70,9 +70,9 @@ fi
 
 # Verify.
 echo 'Checking tokens...'
-#[ -z "${UPLOAD_GITHUB_TOKEN:-}" ] && echo "Missing UPLOAD_GITHUB_TOKEN. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
-#[ -z "${UPLOAD_MODRINTH_TOKEN:-}" ] && echo "Missing UPLOAD_MODRINTH_TOKEN. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
-#[ -z "${UPLOAD_CURSEFORGE_TOKEN:-}" ] && echo "Missing UPLOAD_CURSEFORGE_TOKEN. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
+[ -z "${UPLOAD_GITHUB_TOKEN:-}" ] && echo "Missing UPLOAD_GITHUB_TOKEN. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
+[ -z "${UPLOAD_MODRINTH_TOKEN:-}" ] && echo "Missing UPLOAD_MODRINTH_TOKEN. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
+[ -z "${UPLOAD_CURSEFORGE_TOKEN:-}" ] && echo "Missing UPLOAD_CURSEFORGE_TOKEN. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
 [ -z "${UPLOAD_DISCORD_WEBHOOK:-}" ] && echo "Missing UPLOAD_DISCORD_WEBHOOK. Use '.env' file in 'dev' or your shell's environment variables." && exit 1
 echo 'All tokens found.'
 
@@ -103,30 +103,34 @@ UPLOAD_CHANGELOG_DISCORD_JSON=$(echo "${UPLOAD_CHANGELOG_DISCORD}" | jq --raw-in
 
 # Create a GitHub release draft.
 echo 'Creating a GitHub release draft...'
-#UPLOAD_GITHUB_DRAFT=$(curl --fail-with-body --max-time 30 --retry 3 --request POST --header 'Content-Type: application/json' --header "Authorization: Bearer ${UPLOAD_GITHUB_TOKEN}" --data-raw "{\"tag_name\":${UPLOAD_VERSION_JSON},\"name\":${UPLOAD_NAME_JSON},\"body\":${UPLOAD_CHANGELOG_JSON},\"draft\":true,\"prerelease\":${UPLOAD_VERSION_PRE}}" 'https://api.github.com/repos/VidTu/Ksyxis/releases')
+UPLOAD_GITHUB_DRAFT=$(curl --fail-with-body --max-time 30 --retry 3 --request POST --header 'Content-Type: application/json' --header "Authorization: Bearer ${UPLOAD_GITHUB_TOKEN}" --data-raw "{\"tag_name\":${UPLOAD_VERSION_JSON},\"name\":${UPLOAD_NAME_JSON},\"body\":${UPLOAD_CHANGELOG_JSON},\"draft\":true,\"prerelease\":${UPLOAD_VERSION_PRE}}" 'https://api.github.com/repos/VidTu/Ksyxis/releases')
 echo 'Created a GitHub release draft.'
 
 # Extract the ID.
 echo 'Extracting the GitHub release draft ID...'
-#UPLOAD_GITHUB_ID=$(echo "${UPLOAD_GITHUB_DRAFT}" | jq --raw-output '.id')
-#echo "Extracted the GitHub release draft ID: ${UPLOAD_GITHUB_ID}"
+UPLOAD_GITHUB_ID=$(echo "${UPLOAD_GITHUB_DRAFT}" | jq --raw-output '.id')
+echo "Extracted the GitHub release draft ID: ${UPLOAD_GITHUB_ID}"
 
 # Upload the file to the GitHub release draft.
 echo 'Uploading file to the GitHub release draft...'
-#curl --fail-with-body --max-time 30 --retry 3 --request POST --header 'Content-Type: application/java-archive' --header "Authorization: Bearer ${UPLOAD_GITHUB_TOKEN}" --data-binary "@${UPLOAD_FILE}" "https://uploads.github.com/repos/VidTu/Ksyxis/releases/${UPLOAD_GITHUB_ID}/assets?name=${UPLOAD_FILENAME}"
+curl --fail-with-body --max-time 30 --retry 3 --request POST --header 'Content-Type: application/java-archive' --header "Authorization: Bearer ${UPLOAD_GITHUB_TOKEN}" --data-binary "@${UPLOAD_FILE}" "https://uploads.github.com/repos/VidTu/Ksyxis/releases/${UPLOAD_GITHUB_ID}/assets?name=${UPLOAD_FILENAME}"
 echo 'Uploaded file to the GitHub release draft.'
 
 # Publish a GitHub release from the draft.
 echo 'Publishing a GitHub release from the draft...'
-#curl --fail-with-body --max-time 30 --retry 3 --request PATCH --header 'Content-Type: application/json' --header "Authorization: Bearer ${UPLOAD_GITHUB_TOKEN}" --data-raw "{\"draft\":false}" "https://api.github.com/repos/VidTu/Ksyxis/releases/${UPLOAD_GITHUB_ID}"
+curl --fail-with-body --max-time 30 --retry 3 --request PATCH --header 'Content-Type: application/json' --header "Authorization: Bearer ${UPLOAD_GITHUB_TOKEN}" --data-raw "{\"draft\":false}" "https://api.github.com/repos/VidTu/Ksyxis/releases/${UPLOAD_GITHUB_ID}"
 echo 'Published a GitHub release from the draft.'
 
 # Create a Modrinth release.
 echo 'Publishing a Modrinth release...'
-#curl --fail-with-body --max-time 30 --retry 3 --request POST --header "Authorization: ${UPLOAD_MODRINTH_TOKEN}" --form-string "data={\"name\":${UPLOAD_NAME_JSON},\"version_number\":${UPLOAD_VERSION_JSON},\"changelog\":${UPLOAD_CHANGELOG_MODIFIED_JSON},\"dependencies\":[],\"game_versions\":[\"26.1.2\",\"26.1.1\",\"26.1\",\"1.21.11\",\"1.21.10\",\"1.21.9\",\"1.21.8\",\"1.21.7\",\"1.21.6\",\"1.21.5\",\"1.21.4\",\"1.21.3\",\"1.21.2\",\"1.21.1\",\"1.21\",\"1.20.6\",\"1.20.5\",\"1.20.4\",\"1.20.3\",\"1.20.2\",\"1.20.1\",\"1.20\",\"1.19.4\",\"1.19.3\",\"1.19.2\",\"1.19.1\",\"1.19\",\"1.18.2\",\"1.18.1\",\"1.18\",\"1.17.1\",\"1.17\",\"1.16.5\",\"1.16.4\",\"1.16.3\",\"1.16.2\",\"1.16.1\",\"1.16\",\"1.15.2\",\"1.15.1\",\"1.15\",\"1.14.4\",\"1.14.3\",\"1.14.2\",\"1.14.1\",\"1.14\",\"1.13.2\",\"1.13.1\",\"1.13\",\"1.12.2\",\"1.12.1\",\"1.12\",\"1.11.2\",\"1.11.1\",\"1.11\",\"1.10.2\",\"1.10.1\",\"1.10\",\"1.9.4\",\"1.9.3\",\"1.9.2\",\"1.9.1\",\"1.9\",\"1.8.9\",\"1.8.8\",\"1.8.7\",\"1.8.6\",\"1.8.5\",\"1.8.4\",\"1.8.3\",\"1.8.2\",\"1.8.1\",\"1.8\"],\"version_type\":\"${UPLOAD_VERSION_TYPE}\",\"loaders\":[\"fabric\",\"forge\",\"neoforge\",\"quilt\",\"legacy-fabric\",\"ornithe\"],\"featured\":false,\"status\":\"draft\",\"requested_status\":\"draft\",\"project_id\":\"2ecVyZ49\",\"file_parts\":[\"${UPLOAD_FILENAME}\"],\"primary_file\":\"${UPLOAD_FILENAME}\"}" --form "${UPLOAD_FILENAME}=@${UPLOAD_FILE}" 'https://api.modrinth.com/v2/version'
+curl --fail-with-body --max-time 30 --retry 3 --request POST --header "Authorization: ${UPLOAD_MODRINTH_TOKEN}" --form-string "data={\"name\":${UPLOAD_NAME_JSON},\"version_number\":${UPLOAD_VERSION_JSON},\"changelog\":${UPLOAD_CHANGELOG_MODIFIED_JSON},\"dependencies\":[],\"game_versions\":[\"26.1.2\",\"26.1.1\",\"26.1\",\"1.21.11\",\"1.21.10\",\"1.21.9\",\"1.21.8\",\"1.21.7\",\"1.21.6\",\"1.21.5\",\"1.21.4\",\"1.21.3\",\"1.21.2\",\"1.21.1\",\"1.21\",\"1.20.6\",\"1.20.5\",\"1.20.4\",\"1.20.3\",\"1.20.2\",\"1.20.1\",\"1.20\",\"1.19.4\",\"1.19.3\",\"1.19.2\",\"1.19.1\",\"1.19\",\"1.18.2\",\"1.18.1\",\"1.18\",\"1.17.1\",\"1.17\",\"1.16.5\",\"1.16.4\",\"1.16.3\",\"1.16.2\",\"1.16.1\",\"1.16\",\"1.15.2\",\"1.15.1\",\"1.15\",\"1.14.4\",\"1.14.3\",\"1.14.2\",\"1.14.1\",\"1.14\",\"1.13.2\",\"1.13.1\",\"1.13\",\"1.12.2\",\"1.12.1\",\"1.12\",\"1.11.2\",\"1.11.1\",\"1.11\",\"1.10.2\",\"1.10.1\",\"1.10\",\"1.9.4\",\"1.9.3\",\"1.9.2\",\"1.9.1\",\"1.9\",\"1.8.9\",\"1.8.8\",\"1.8.7\",\"1.8.6\",\"1.8.5\",\"1.8.4\",\"1.8.3\",\"1.8.2\",\"1.8.1\",\"1.8\"],\"version_type\":\"${UPLOAD_VERSION_TYPE}\",\"loaders\":[\"fabric\",\"forge\",\"neoforge\",\"quilt\",\"legacy-fabric\",\"ornithe\"],\"featured\":false,\"status\":\"listed\",\"requested_status\":\"listed\",\"project_id\":\"2ecVyZ49\",\"file_parts\":[\"${UPLOAD_FILENAME}\"],\"primary_file\":\"${UPLOAD_FILENAME}\"}" --form "${UPLOAD_FILENAME}=@${UPLOAD_FILE}" 'https://api.modrinth.com/v2/version'
 echo 'Published a Modrinth release.'
 
-# TODO CURSEFORGE.
+# Create a CurseForge release.
+# Obtain versions: curl https://api.curseforge.com/v1/minecraft/version | jq -r '.data.[] | .versionString + ": " + (.gameVersionId|tostring)'
+echo 'Publishing a CurseForge release...'
+curl --fail-with-body --max-time 30 --retry 3 --request POST --header "X-Api-Token: ${UPLOAD_CURSEFORGE_TOKEN}" --form-string "metadata={\"changelog\":${UPLOAD_CHANGELOG_MODIFIED_JSON},\"changelogType\":\"markdown\",\"displayName\":${UPLOAD_NAME_JSON},\"gameVersions\":[16082,16021,15933,14406,13964,13927,13620,13506,13422,12934,12281,12084,12079,11779,11457,11198,11163,10407,10395,10236,9990,9971,9776,9550,9366,9259,9186,9008,8857,8830,8516,8152,8203,8134,8056,8010,7892,7890,7722,7675,7664,7469,7413,7361,7344,7318,7132,7107,7081,6756,6711,6580,6452,6451,6317,6170,6160,6144,6084,6085,5997,5998,5946,5806,5703,5642,4480,4479,4478,4466,4465,4463,4455],\"releaseType\":\"${UPLOAD_VERSION_TYPE}\"}" 'https://minecraft.curseforge.com/api/projects/537533/upload-file'
+echo 'Published a CurseForge release.'
 
 # Notify via Discord webhook.
 echo 'Publishing a Discord webhook...'
